spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop   # 테스트 시작 시 생성, 끝나면 삭제
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging.level.org.hibernate.SQL: warn