spring:
  application:
    name: hyu
  profiles:
    # 명시 안 하면 dev로 동작
    default: dev
  config:
    # 존재하면 자동 병합 (비밀/개인 설정은 -local.yml에서만 관리)
    import: optional:application-${spring.profiles.active}-local.yml

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        # 필요하면 주석 해제
        # jdbc.time_zone: UTC

# Actuator 공통 노출(필요 최소)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized  # dev/test 프로필에서만 always로 오버라이드

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: off
    org.hibernate.orm.jdbc.extract: off

jwt:
  # 운영/CI에서는 환경변수 JWT_SECRET 로 덮어쓰기
  secret: ${JWT_SECRET:please-change-me-to-256bit-string-32bytes-min}
  validity-millis: 21600000          # 6시간
  refresh-validity-millis: 1209600000 # 14일
  refresh-cookie-name: RT
  refresh-cookie-secure: false        # 운영에서는 true 로 전환
  # refresh-cookie-domain: (도메인 쓰면 명시)