spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: app
    password: app
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop   # 테스트 시작 시 생성, 끝나면 삭제
    properties:
      hibernate:
        format_sql: true

logging.level.org.hibernate.SQL: warn